# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: josegba12
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-lamda-crud-node
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-crud-node

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AtrributeType: S
      KeySchema:
        - AtributeName: id
          KeyType: HASH